import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import "./globals.css";
import { ThemeProvider } from 'next-themes';
import { Analytics } from '@vercel/analytics/next';
import ClientWrapper from '../components/ClientWrapper';

export const metadata: Metadata = {
  title: "Raghav Dadhich",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false} forcedTheme={undefined}>
          <ClientWrapper>
            {children}
          </ClientWrapper>
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  );
}
